import{a as y,S as h,i as u}from"./assets/vendor-b11e2a50.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const F="44714741-6fe0dcbbee03096a14c34d671",b="https://pixabay.com/api/";async function C(o,s=1,t=15){const n=`${b}?key=${F}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&page=${s}&per_page=${t}`;try{const e=await y.get(n);if(e.status!==200)throw new Error("Network response was not ok");return e.data.hits}catch(e){throw console.error("Error fetching images:",e),e}}const g=document.querySelector(".gallery"),m=new h(".gallery a");function w(){g.innerHTML="",m.refresh()}function L(o){const s=o.map(t=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${t.largeImageURL}">
                <div class="large-img">
                    <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}">
                    <ul class="img-details">
                        <li><p>Likes</p><p>${t.likes}</p></li>
                        <li><p>Views</p><p>${t.views}</p></li>
                        <li><p>Comments</p><p>${t.comments}</p></li>
                        <li><p>Downloads</p><p>${t.downloads}</p></li>
                    </ul>
                </div>
            </a>
        </li>
    `).join("");g.insertAdjacentHTML("beforeend",s),m.refresh()}let c="",l=1;const E=document.querySelector(".search-form"),p=document.querySelector(".search-input"),a=document.querySelector(".loader"),i=document.querySelector(".load-more"),$=document.querySelector(".gallery");E.addEventListener("submit",async function(o){if(o.preventDefault(),c=p.value.trim(),c===""){u.error({title:"Error",message:"Please enter a search term.",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFF",titleColor:"#FFF",iconColor:"#FFF",timeout:5e3});return}p.value="",l=1,w(),await f(c,l)});i.addEventListener("click",async function(){l++,i.textContent="Loading images, please wait...",i.disabled=!0,await f(c,l),i.textContent="Load more",i.disabled=!1});async function f(o,s){a.textContent="Loading images, please wait...",a.style.display="block";try{const t=await C(o,s);a.style.display="none",t.length===0?u.info({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFF",titleColor:"#FFF",iconColor:"#FFF",timeout:5e3}):(L(t),l===1&&(i.style.display="inline-block"),v(),S(t.length))}catch(t){a.style.display="none",u.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFF",titleColor:"#FFF",iconColor:"#FFF",timeout:5e3}),console.error("Error fetching images:",t)}}function v(){const o=$.getBoundingClientRect().height;window.scrollBy({top:o,behavior:"smooth"})}function S(o){o<15?(i.style.display="none",u.info({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFF",titleColor:"#FFF",iconColor:"#FFF",timeout:5e3})):i.style.display="inline-block"}
//# sourceMappingURL=commonHelpers.js.map
